# Generated by Django 3.2.23 on 2024-02-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWeb', '0002_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='phone',
            field=models.CharField(default='none', max_length=15),
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
