# Generated by Django 3.2.23 on 2024-02-05 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWeb', '0002_courses_register_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Register',
        ),
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='user',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
