# Generated by Django 3.2.23 on 2024-02-01 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWeb', '0003_auto_20240201_1940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='User',
        ),
    ]
