# Generated by Django 3.2.23 on 2024-02-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWeb', '0004_alter_user_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user',
        ),
    ]
