# Generated by Django 3.2.23 on 2024-02-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWeb', '0008_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
