# Generated by Django 3.2.23 on 2024-02-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWeb', '0009_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
