# Generated by Django 3.2.23 on 2024-02-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWeb', '0010_auto_20240202_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmPassword',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
