# Generated by Django 3.2.23 on 2024-02-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWeb', '0013_alter_user_confirmpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
