# Generated by Django 3.2.23 on 2024-02-02 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWeb', '0017_auto_20240202_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirmPassword',
        ),
    ]
