# Generated by Django 3.2.23 on 2024-02-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myWeb', '0022_user_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
