# Generated by Django 3.2.23 on 2024-02-02 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myWeb', '0023_alter_user_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
